### ISSUE TITLE
Is there any release version

### ISSUE THREAD

**Issue by xiaoyao9184** [TheDiveO/lxkns#15]
hi,
Is there a compiled version available for download, including the GUI service docker image.

**Comment by TheDiveO** [comment]
Unfortunately, no. My reasoning so far is as follows:
- the CLI tools are highly specific and their console output not necessarily easy to grok, so the service with API and UI looks to me more promising. In consequence, I would expect more or less no demand for binaries.
- the UI needs its files be present and in the past, Go had no means to integrate the UI resources files into a single binary. Admittedly, the situation has become well in this respect.
- deploying the service as root isn't something I endorse, so container deployment is a much better way. Unfortunately, container images eat into my account limits very quickly, so I won't offer images. Maybe Docker hub might be a way, but that's another integration causing work and friction.
- In the end, since around Go 1.13 or later, Go modules became useful, so building either the CLI binaries or the containerized service is a comparably easy and reliable method. Especially due to the ugly Javascript-npm-yarn package hell.

In general, Go is well supported on all major distributions. Git clone the repository, cd into it, do `make deploy` and that's it. You can then use the image also elsewhere. Or `make install` for the CLI binaries to be build and installed into (often) `$HOME/go/bin`.

**Comment by TheDiveO** [comment]
If you have further questions please feel free to reopen this issue if you think they belong to this thread, or open a new issue for new topics.

One thing I forgot to mention in my reasoning is that any lxkns Service Image will never run without a bunch of deployment options, most of them security-related. Unfortunately, there's no more or less adopted method of distributing not only the image but also the deployment configuration.

**Comment by thediveo** [comment]
It's more than a year since the original request: there's finally the directly deployable (or is that "deplorable"?) service container image available from ghcr.io/thediveo/lxkns. With a recent Docker and especially Docker composer plugin v2 installed, just issue:

```dockerfile
wget -q -O - \
  https://github.com/thediveo/lxkns/raw/master/deployments/wget/docker-compose.yaml \
  | docker compose -f - up
```

Then, navigate to http://localhost:5010.

The image is multi-architecture for limux/amd64 and linux/arm64.
